import { Portal, BidData, TodayStats } from '@/types';

export const mockPortals: Portal[] = [
  {
    id: 'portal-1',
    name: 'Metro Government Portal',
    url: 'https://metro.gov/bids',
    username: 'biduser1',
    password: '***********',
    status: 'active',
    lastChecked: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    bidCount: 45,
    type: 'government',
  },
  {
    id: 'portal-2',
    name: 'OhioBuys',
    url: 'https://ohiobuys.gov',
    username: 'biduser2',
    password: '***********',
    status: 'active',
    lastChecked: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    bidCount: 32,
    type: 'government',
  },
  {
    id: 'portal-3',
    name: 'Federal Business Opportunities',
    url: 'https://fbo.gov',
    username: 'biduser3',
    password: '***********',
    status: 'inactive',
    lastChecked: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    bidCount: 18,
    type: 'government',
  },
  {
    id: 'portal-4',
    name: 'City Contract Portal',
    url: 'https://citycontracts.gov',
    username: 'biduser4',
    password: '***********',
    status: 'error',
    lastChecked: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    bidCount: 0,
    type: 'government',
  },
];

export const mockBidData: BidData[] = [
  {
    id: 'bid-1',
    title: 'Road Maintenance Services',
    description: 'Comprehensive road maintenance and repair services for downtown area',
    portalId: 'portal-1',
    portalName: 'Metro Government Portal',
    bidNumber: 'RFP-2024-001',
    agency: 'Department of Transportation',
    amount: 2500000,
    currency: 'USD',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    publishedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Infrastructure',
    location: 'Nashville, TN',
    status: 'open',
    tags: ['road', 'maintenance', 'transportation'],
    contactInfo: {
      name: 'John Smith',
      email: 'john.smith@metro.gov',
      phone: '615-555-0123',
    },
    documents: [
      {
        name: 'RFP Document',
        url: '/documents/rfp-2024-001.pdf',
        type: 'pdf',
      },
      {
        name: 'Technical Specifications',
        url: '/documents/tech-specs-001.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 'bid-2',
    title: 'IT Support Services',
    description: 'Managed IT support services for city government offices',
    portalId: 'portal-2',
    portalName: 'OhioBuys',
    bidNumber: 'RFP-2024-002',
    agency: 'Information Technology Department',
    amount: 1200000,
    currency: 'USD',
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    publishedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Technology',
    location: 'Columbus, OH',
    status: 'open',
    tags: ['IT', 'support', 'technology', 'managed services'],
    contactInfo: {
      name: 'Sarah Johnson',
      email: 'sarah.johnson@ohio.gov',
      phone: '614-555-0456',
    },
    documents: [
      {
        name: 'Statement of Work',
        url: '/documents/sow-2024-002.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 'bid-3',
    title: 'Park Landscaping Project',
    description: 'Landscaping and beautification of Central Park area',
    portalId: 'portal-1',
    portalName: 'Metro Government Portal',
    bidNumber: 'RFP-2024-003',
    agency: 'Parks and Recreation',
    amount: 750000,
    currency: 'USD',
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    publishedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Recreation',
    location: 'Nashville, TN',
    status: 'open',
    tags: ['landscaping', 'parks', 'beautification'],
    contactInfo: {
      name: 'Mike Davis',
      email: 'mike.davis@metro.gov',
      phone: '615-555-0789',
    },
    documents: [
      {
        name: 'Project Plans',
        url: '/documents/park-plans-003.pdf',
        type: 'pdf',
      },
      {
        name: 'Site Survey',
        url: '/documents/site-survey-003.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 'bid-4',
    title: 'Security Services Contract',
    description: 'Security services for government buildings and facilities',
    portalId: 'portal-2',
    portalName: 'OhioBuys',
    bidNumber: 'RFP-2024-004',
    agency: 'General Services Administration',
    amount: 3200000,
    currency: 'USD',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    publishedDate: new Date().toISOString(),
    category: 'Security',
    location: 'Statewide, OH',
    status: 'open',
    tags: ['security', 'guards', 'facilities'],
    contactInfo: {
      name: 'Lisa Wilson',
      email: 'lisa.wilson@ohio.gov',
      phone: '614-555-0321',
    },
    documents: [
      {
        name: 'Security Requirements',
        url: '/documents/security-req-004.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 'bid-5',
    title: 'Office Supply Contract',
    description: 'Annual office supplies and equipment procurement',
    portalId: 'portal-3',
    portalName: 'Federal Business Opportunities',
    bidNumber: 'RFP-2024-005',
    agency: 'General Services Administration',
    amount: 500000,
    currency: 'USD',
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    publishedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Supplies',
    location: 'Federal Wide',
    status: 'closed',
    tags: ['office', 'supplies', 'equipment'],
    contactInfo: {
      name: 'Robert Brown',
      email: 'robert.brown@gsa.gov',
      phone: '202-555-0654',
    },
    documents: [
      {
        name: 'Supply List',
        url: '/documents/supply-list-005.pdf',
        type: 'pdf',
      },
    ],
  },
];

export const mockTodayStats: TodayStats = {
  totalBids: 127,
  newBids: 23,
  activePortals: 3,
  totalPortals: 4,
  lastUpdate: new Date().toISOString(),
  bidsByPortal: {
    'portal-1': {
      name: 'Metro Government Portal',
      count: 45,
      percentage: 35,
    },
    'portal-2': {
      name: 'OhioBuys',
      count: 32,
      percentage: 25,
    },
    'portal-3': {
      name: 'Federal Business Opportunities',
      count: 18,
      percentage: 14,
    },
    'portal-4': {
      name: 'City Contract Portal',
      count: 32,
      percentage: 26,
    },
  },
  bidsByCategory: {
    'Infrastructure': 35,
    'Technology': 28,
    'Security': 22,
    'Recreation': 18,
    'Supplies': 14,
    'Healthcare': 10,
  },
  bidsByStatus: {
    open: 95,
    closed: 20,
    awarded: 8,
    cancelled: 4,
  },
};